In [1]:
import pandas as pd
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
from sqlalchemy import create_engine, text
import geopandas as gpd
from geopy.geocoders import Nominatim
from shapely.geometry import Point
import requests
import io

### Investigating DuckDB:

I'll use DuckDB for this project since the datasets I'll be using (especially HCRIS) are expected to be very large. DuckDB integrates well with Python ecosystems and will allow me to query in-memory data frames without copying the data.

In [2]:
import duckdb

In [3]:
result = duckdb.sql('SELECT 42')
result.show()

┌───────┐
│  42   │
│ int32 │
├───────┤
│    42 │
└───────┘

We ran the SQL statement above on the duckdb object we imported
into our program. We didn’t acquire or use a dedicated connection object. The
duckdb object provided us with a default, in-memory connection. Of course, you can
use a dedicated connection too.

In [4]:
con = duckdb.connect(database=':memory:')

In [5]:
con.execute('LOAD httpfs; LOAD excel') # Load the httpfs extension. You need to do this each time you initialize a new database.

Example of using DuckDB to query a DataFrame:

In [6]:
people = pd.DataFrame({
'name': ['Michael Hunger', 'Michael Simons', 'Mark Needham'],
'country': ['Germany', 'Germany', 'Great Britain']
})

In [7]:
duckdb.sql('''
SELECT *
FROM people
WHERE country = 'Germany'
''')

┌────────────────┬─────────┐
│      name      │ country │
│    varchar     │ varchar │
├────────────────┼─────────┤
│ Michael Hunger │ Germany │
│ Michael Simons │ Germany │
└────────────────┴─────────┘

In [8]:
params = {'country': 'Germany'}
duckdb.execute('''
SELECT *
FROM people
WHERE country <> $country
''', params).fetchdf()

           name        country
0  Mark Needham  Great Britain

Our recommendation for both Polars and pandas is to stick to the relational or data-
base API as long as possible and convert to a DataFrame only if you need to combine it
with external data or if a computation via SQL would just not be feasible

### Data Gathering:

Before downloading any yearly data, I'll create one main hospital-level table (hospitals_master) with one row per hospital to serve as a base for the project. The table will contain information such as: 


CMS Certification Number (CCN)  \
NPI     \
Facility name    \
Address \
County FIPS code       \
State  

The initial scope of the project will just be US rural acute care hospitals. This will ensure financial reporting metrics and quality metrics are as comparable as possible.

Possible additional datasets to look into: 

This dataset has facility name, address, state, and CCN for hospitals over the past 7 years: https://data.cms.gov/provider-data/dataset/xubh-q36u#data-table (Facility ID = CCN)

This dataset has facility name, address, state, CCN, and FIPS code for hospitals in 2022: https://www.shepscenter.unc.edu/download/25637/?tmstv=1779849485

In [9]:
cms_providers = pd.read_csv('../data/Hospital_General_Information.csv')

In [10]:
cms_providers.head()

,Facility ID,Facility Name,Address,City/Town,State,ZIP Code,County/Parish,Telephone Number,Hospital Type,Hospital Ownership,...,Count of READM Measures Better,Count of READM Measures No Different,Count of READM Measures Worse,READM Group Footnote,Pt Exp Group Measure Count,Count of Facility Pt Exp Measures,Pt Exp Group Footnote,TE Group Measure Count,Count of Facility TE Measures,TE Group Footnote
0,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,Acute Care Hospitals,Government - Hospital District or Authority,...,1,9,1,NaN,15,15,NaN,10,10,NaN
1,010005,MARSHALL MEDICAL CENTERS,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,(256) 593-8310,Acute Care Hospitals,Government - Hospital District or Authority,...,1,8,0,NaN,15,15,NaN,10,10,NaN
2,010006,NORTH ALABAMA MEDICAL CENTER,1701 VETERANS DRIVE,FLORENCE,AL,35630,LAUDERDALE,(256) 768-8400,Acute Care Hospitals,Proprietary,...,1,8,0,NaN,15,15,NaN,10,9,NaN
3,010007,MIZELL MEMORIAL HOSPITAL,702 N MAIN ST,OPP,AL,36467,COVINGTON,(334) 493-3541,Acute Care Hospitals,Voluntary non-profit - Private,...,0,3,2,NaN,15,5,NaN,10,7,NaN
4,010011,ST. VINCENT'S EAST,50 MEDICAL PARK EAST DRIVE,BIRMINGHAM,AL,35235,JEFFERSON,(205) 838-3122,Acute Care Hospitals,Voluntary non-profit - Private,...,1,5,2,29.0,15,10,29.0,10,7,29.0

In [11]:
cms_providers.columns

Index(['Facility ID', 'Facility Name', 'Address', 'City/Town', 'State',
       'ZIP Code', 'County/Parish', 'Telephone Number', 'Hospital Type',
       'Hospital Ownership', 'Emergency Services',
       'Meets criteria for birthing friendly designation',
       'Hospital overall rating', 'Hospital overall rating footnote',
       'MORT Group Measure Count', 'Count of Facility MORT Measures',
       'Count of MORT Measures Better', 'Count of MORT Measures No Different',
       'Count of MORT Measures Worse', 'MORT Group Footnote',
       'Safety Group Measure Count', 'Count of Facility Safety Measures',
       'Count of Safety Measures Better',
       'Count of Safety Measures No Different',
       'Count of Safety Measures Worse', 'Safety Group Footnote',
       'READM Group Measure Count', 'Count of Facility READM Measures',
       'Count of READM Measures Better',
       'Count of READM Measures No Different', 'Count of READM Measures Worse',
       'READM Group Footnote', 'Pt Exp Group Measure Count',
       'Count of Facility Pt Exp Measures', 'Pt Exp Group Footnote',
       'TE Group Measure Count', 'Count of Facility TE Measures',
       'TE Group Footnote'],
      dtype='object')

In [12]:
cms_providers['Hospital Type'].unique()

array(['Acute Care Hospitals', 'Acute Care - Veterans Administration',
       'Rural Emergency Hospital', 'Critical Access Hospitals',
       'Childrens', 'Psychiatric', 'Acute Care - Department of Defense',
       'Long-term'], dtype=object)

Narrowing down to just Acute Care Hospitals:

In [13]:
cms_providers = cms_providers[cms_providers['Hospital Type'] == 'Acute Care Hospitals']

Selecting only the columns that we need:

In [14]:
cms_providers = cms_providers[['Facility ID', 'Facility Name', 'Address', 'City/Town', 'State', 'ZIP Code', 'County/Parish', 'Emergency Services','Hospital Ownership']]

Renaming Facility ID to CCN for clarity:

In [15]:
cms_providers = cms_providers.rename(columns={'Facility ID': 'CCN', 'County/Parish': 'County', 'City/Town': 'City', 'ZIP Code': 'Zip'})

Adding a Closure column and setting to 0 since these hospitals are currently open.

In [16]:
 cms_providers['Closed'] = 0

In [17]:
cms_providers.head(2)

,CCN,Facility Name,Address,City,State,Zip,County,Emergency Services,Hospital Ownership,Closed
0,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,Yes,Government - Hospital District or Authority,0
1,010005,MARSHALL MEDICAL CENTERS,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,Yes,Government - Hospital District or Authority,0

Reading in rural hospital closures data:

In [18]:
rural_hospital_closures = pd.read_excel('../data/Closures-Database-for-Web.xlsx')

In [19]:
rural_hospital_closures.head()

,Hospital,Address,City,State,Zip,County/district,RUCA,CBSA,Medicare Payment,# of Beds,Closure Month,Closure Year,Complete Closure (0);\nConverted Closure (1),updated 5/18/2025
0,Bradford Regional Medical Center,116 INTERSTATE PARKWAY,BRADFORD,PA,16701.0,McKean,4.0,Micro,PPS,14.0,May,2026.0,1,196 Closed Rural Hospitals 2005-2026
1,Claremore Indian Hospital,101 South Moore Ave,Claremore,OK,74017.0,Rogers,4.0,Metro,IHS,46.0,October,2025.0,1,88 Converted to other health services
2,Glenn Medical Center,1133 W SYCAMORE ST,WILLOWS,CA,95988.0,Glenn,7.0,Neither,CAH,25.0,September,2025.0,1,NaN
3,Northern Light Inland Hospital,200 KENNEDY MEMORIAL DRIVE,WATERVILLE,ME,4901.0,Kennebec,4.0,Micro,MDH,33.0,May,2025.0,0,NaN
4,Lawrence Medical Center,202 HOSPITAL STREET,MOULTON,AL,35650.0,Lawrence,7.0,Metro,PPS,43.0,May,2025.0,1,NaN

In [20]:
rural_hospital_closures.columns

Index(['Hospital', 'Address', 'City', 'State', 'Zip', 'County/district',
       'RUCA', 'CBSA', 'Medicare Payment', '# of Beds', 'Closure Month',
       'Closure Year', 'Complete Closure (0);\nConverted Closure (1)',
       'updated 5/18/2025'],
      dtype='object')

Updating closure column so that complete closure = 2 and converted closure = 1:

In [21]:
rural_hospital_closures = rural_hospital_closures.rename(columns={'Complete Closure (0);\nConverted Closure (1)': 'Closed', 'County/district':'County', '# of Beds':'Number of Beds','Hospital':'Facility Name'})

In [22]:
rural_hospital_closures['Closed'] = rural_hospital_closures['Closed'].replace(0,2)

Remove footer:

In [23]:
rural_hospital_closures = rural_hospital_closures[rural_hospital_closures['Closed'] != '88 Converted to other health services']

Narrow down to just the columns we need and drop any fully null rows:

In [24]:
rural_hospital_closures = (rural_hospital_closures.drop(columns='updated 5/18/2025').dropna(how='all'))

Cast ZIP, number of beds, and closure year to integer:

In [25]:
rural_hospital_closures[['Zip','Number of Beds','Closure Year']] = rural_hospital_closures[['Zip','Number of Beds','Closure Year']].astype(int)

Convert closure month/year to date:

In [26]:
rural_hospital_closures['Closure Month'] = pd.to_datetime(rural_hospital_closures['Closure Month'], format='%B', errors='coerce').dt.month

In [27]:
rural_hospital_closures = rural_hospital_closures.rename(columns={'Closure Year':'year', 'Closure Month':'month'})

In [28]:
rural_hospital_closures['Closure Date'] = pd.to_datetime(rural_hospital_closures[['year', 'month']].assign(day=1))

In [29]:
rural_hospital_closures = rural_hospital_closures.drop(columns=['year','month'])

In [30]:
rural_hospital_closures.head(2)

,Facility Name,Address,City,State,Zip,County,RUCA,CBSA,Medicare Payment,Number of Beds,Closed,Closure Date
0,Bradford Regional Medical Center,116 INTERSTATE PARKWAY,BRADFORD,PA,16701,McKean,4.0,Micro,PPS,14,1,2026-05-01
1,Claremore Indian Hospital,101 South Moore Ave,Claremore,OK,74017,Rogers,4.0,Metro,IHS,46,1,2025-10-01

In [35]:
rural_hospital_closures['Closed'].value_counts()

Closed
2    108
1     88
Name: count, dtype: int64

Combine currently active hospital data with closed hospital data:

In [36]:
hospitals_master = pd.concat([cms_providers, rural_hospital_closures]).reset_index()

Uppercase all hospital names and addresses for consistency:

In [37]:
hospitals_master[['Facility Name','Address', 'City', 'State', 'County']] = (
                                                                                     hospitals_master[['Facility Name','Address', 'City', 'State', 'County']]
                                                                                     .apply(lambda x : x.str.upper())
                                                                                    )

Pre-process addresses to help with geocoding:

In [38]:
# Keep only the first comma-delimited segment (Some addresses already contain the city and state; we'll strip that off.)
hospitals_master['Address'] = hospitals_master['Address'].str.split(",").str[0]

# Remove suite / box / mail-slot style text
hospitals_master['Address'] = (
    hospitals_master['Address']
    .str.replace(
        r"\s*(?:SUITE|UNIT|STE|PO BOX|BOX|P O BOX|POST OFFICE BOX|MAIL SLOT)\s*\.?\s*\d+",
        "",
        case=False,
        regex=True,
    )
    .str.strip()
)

# Expand common written numbers / ordinals
mapping = {
    "FIRST ": "1ST ",
    "SECOND ": "2ND ",
    "THIRD ": "3RD ",
    "FOURTH ": "4TH ",
    "FIFTH ": "5TH ",
    "SIXTH ": "6TH ",
    "SEVENTH ": "7TH ",
    "EIGHTH ": "8TH ",
    "NINTH ": "9TH ",
    "TENTH ": "10TH ",
    "ONE ": "1 ",
    "TWO ": "2 ",
    "THREE ": "3 ",
    "FOUR ": "4 ",
    "FIVE ": "5 ",
    "SIX ": "6 ",
    "SEVEN ": "7 ",
    "EIGHT ": "8 ",
    "NINE ": "9 ",
    "TEN ": "10 ",
    "TWNSHP PRKWY": "TOWNSHIP PARKWAY",
}

for word, replacement in mapping.items():
    hospitals_master['Address'] = hospitals_master['Address'].str.replace(word, replacement, regex=False)

Combine address parts to make a full address column.

In [39]:
hospitals_master['Full Address'] = (
        hospitals_master['Address'] + ", " +
        hospitals_master['City'] + ", " +
        hospitals_master['State'] + ", " +
        hospitals_master['Zip'].astype(str)
    )

In [40]:
hospitals_master

,index,CCN,Facility Name,Address,City,State,Zip,County,Emergency Services,Hospital Ownership,Closed,RUCA,CBSA,Medicare Payment,Number of Beds,Closure Date,Full Address
0,0,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,Yes,Government - Hospital District or Authority,0,NaN,NaN,NaN,NaN,NaT,"1108 ROSS CLARK CIRCLE, DOTHAN, AL, 36301"
1,1,010005,MARSHALL MEDICAL CENTERS,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,Yes,Government - Hospital District or Authority,0,NaN,NaN,NaN,NaN,NaT,"2505 U S HIGHWAY 431 NORTH, BOAZ, AL, 35957"
2,2,010006,NORTH ALABAMA MEDICAL CENTER,1701 VETERANS DRIVE,FLORENCE,AL,35630,LAUDERDALE,Yes,Proprietary,0,NaN,NaN,NaN,NaN,NaT,"1701 VETERANS DRIVE, FLORENCE, AL, 35630"
3,3,010007,MIZELL MEMORIAL HOSPITAL,702 N MAIN ST,OPP,AL,36467,COVINGTON,Yes,Voluntary non-profit - Private,0,NaN,NaN,NaN,NaN,NaT,"702 N MAIN ST, OPP, AL, 36467"
4,4,010011,ST. VINCENT'S EAST,50 MEDICAL PARK EAST DRIVE,BIRMINGHAM,AL,35235,JEFFERSON,Yes,Voluntary non-profit - Private,0,NaN,NaN,NaN,NaN,NaT,"50 MEDICAL PARK EAST DRIVE, BIRMINGHAM, AL, 35235"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3306,191,NaN,FAYETTE MEMORIAL HOSPITAL,543 N JACKSON,LA GRANGE,TX,78945,FAYETTE,NaN,NaN,2,7.0,Neither,PPS,24.0,2005-07-01,"543 N JACKSON, LA GRANGE, TX, 78945"
3307,192,NaN,DELEON HOSPITAL,407 S TEXAS,DE LEON,TX,76444,COMANCHE,NaN,NaN,2,10.0,Neither,CAH,14.0,2005-07-01,"407 S TEXAS, DE LEON, TX, 76444"
3308,193,NaN,MINNEWASKA DISTRICT HOSP,610 W 6TH ST,STARBUCK,MN,56381,POPE,NaN,NaN,2,10.0,Neither,CAH,19.0,2005-06-01,"610 W 6TH ST, STARBUCK, MN, 56381"
3309,194,NaN,GULF PINES HOSPITAL,102 20TH ST,PORT SAINT JOE,FL,32456,GULF,NaN,NaN,2,7.1,Metro,PPS,45.0,2005-03-01,"102 20TH ST, PORT SAINT JOE, FL, 32456"
3310,195,NaN,KINGS DAUGHTERS HOSPITAL-GREENVILLE,300 SOUTH WASHINGTON AVENUE,GREENVILLE,MS,38701,WASHINGTON,NaN,NaN,1,4.0,Micro,PPS,99.0,2005-03-01,"300 SOUTH WASHINGTON AVENUE, GREENVILLE, MS, 3..."

In [41]:
hospitals_master.shape

(3311, 17)

Now we'll use the US Census Bureau's geocoder tool to pull in FIPS codes as well as census tract numbers.

In [42]:
addresses = (hospitals_master
             [['Address','City','State','Zip']]
             .rename(columns={'Address':'Street Address','Zip':'Zip Code'})
            )

addresses.to_csv('../data/addresses.csv', header=False)

In [43]:
addresses.shape

(3311, 4)

In [44]:
# Define endpoint and parameters
url = "https://geocoding.geo.census.gov/geocoder/geographies/addressbatch"
payload = {
    'benchmark': 'Public_AR_Current',
    'vintage': 'Current_Current' 
}

# Open csv file and send post request
file_path = "../data/addresses.csv"
files = {'addressFile': (file_path, open(file_path, 'rb'), 'text/csv')}

response = requests.post(url, files=files, data=payload)

# Parse the output into a DataFrame
# The census API returns a csv-like text string. We name the expected columns based on the API documentation.
column_names = [
    'Unique_ID', 'Input_Address', 'Match_Status', 'Match_Type', 'Matched_Address', 
    'Coordinates', 'Tiger_Line_ID', 'Tiger_Side', 'State_FIPS', 'County_FIPS', 
    'Tract_Code', 'Block_Code'
]

if response.status_code == 200:
    res_df = pd.read_csv(io.StringIO(response.text), header=None, names=column_names)[['Input_Address','Coordinates','State_FIPS','County_FIPS','Tract_Code']]
    hospitals_master_geo = hospitals_master.merge(res_df, left_on='Full Address', right_on='Input_Address', how='left')
else:
    print(f"Error: {response.status_code}")

I also geocoded with Nominatim which resulted in a few hundred more facilities able to be successfully geocoded. Reading in that data:

In [45]:
nom = pd.read_csv('../data/nominatim_geocoded.csv')

In [46]:
hospitals_master_geo_full = hospitals_master_geo.merge(nom, on=['Facility Name','Address'], how='left')

In [47]:
# Coalesce the coordinates column using combine_first
hospitals_master_geo_full['Coordinates'] = hospitals_master_geo_full['Coordinates_x'].combine_first(hospitals_master_geo_full['Coordinates_y'])

# Clean up unneeded columns and drop duplicated rows
hospitals_master_geo_full = hospitals_master_geo_full.drop(columns=['Coordinates_x', 'Coordinates_y', 'Input_Address','index']).drop_duplicates()

In [48]:
hospitals_master_geo_full.head(2)

,CCN,Facility Name,Address,City,State,Zip,County,Emergency Services,Hospital Ownership,Closed,RUCA,CBSA,Medicare Payment,Number of Beds,Closure Date,Full Address,State_FIPS,County_FIPS,Tract_Code,Coordinates
0,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,Yes,Government - Hospital District or Authority,0,NaN,NaN,NaN,NaN,NaT,"1108 ROSS CLARK CIRCLE, DOTHAN, AL, 36301",1.0,69.0,41000.0,"-85.361446991439,31.21566695385"
1,010005,MARSHALL MEDICAL CENTERS,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,Yes,Government - Hospital District or Authority,0,NaN,NaN,NaN,NaN,NaT,"2505 U S HIGHWAY 431 NORTH, BOAZ, AL, 35957",1.0,95.0,31200.0,"-86.159366335505,34.221221654827"

In [49]:
hospitals_master_geo_full[hospitals_master_geo_full['Coordinates'].isna()][['Facility Name', 'Full Address']]

,Facility Name,Full Address
31,RUSSELL MEDICAL CENTER,"3316 HIGHWAY 280, ALEXANDER CITY, AL, 35010"
32,CLAY COUNTY HOSPITAL,"83825 HIGHWAY 9, ASHLAND, AL, 36251"
52,WHITFIELD REGIONAL HOSPITAL,"105 HIGHWAY 80 EAST, DEMOPOLIS, AL, 36732"
57,LAKELAND COMMUNITY HOSPITAL,"42024 HIGHWAY 195 E, HALEYVILLE, AL, 35565"
70,RUSSELLVILLE HOSPITAL,"15155 HIGHWAY 43, RUSSELLVILLE, AL, 35653"
80,YUKON KUSKOKWIM DELTA REG HOSPITAL,", BETHEL, AK, 99559"
106,FORT DEFIANCE INDIAN HOSPITAL,", FT. DEFIANCE, AZ, 86504"
107,TUBA CITY REGIONAL HEALTH CARE CORPORATION,", TUBA CITY, AZ, 86045"
319,PROVIDENCE ST MARY MEDICAL CENTER,"18300 HIGHWAY 18, APPLE VALLEY, CA, 92307"
1261,NORTHERN LIGHT A R GOULD HOSPITAL,", PRESQUE ISLE, ME, 4769"
1500,HUTCHINSON HEALTH,"1095 HIGHWAY 15 SOUTH, HUTCHINSON, MN, 55350"
1558,ALLIANCE HEALTH CENTER,"5000 HIGHWAY 39 NORTH, MERIDIAN, MS, 39301"
1573,MERCY HOSPITAL JEFFERSON,"1400 US HIGHWAY 61, CRYSTAL CITY, MO, 63019"
1640,CHI HEALTH GOOD SAMARITAN,", KEARNEY, NE, 68848"
1976,MARIA PARHAM MEDICAL CENTER,", HENDERSON, NC, 27536"
2002,P H S INDIAN HOSP AT BELCOURT-QUENTIN N BURDICK,", BELCOURT, ND, 58316"
2730,THE UNIVERSITY OF TEXAS HEALTH SCIENCE CENTER ...,"11937 US HIGHWAY 271, TYLER, TX, 75708"
2821,CENTRAL VERMONT MEDICAL CENTER,", BARRE, VT, 5641"
2877,HIRAM W DAVIS MEDICAL CENTER,", PETERSBURG, VA, 23803"
3042,ST JOHNS MEDICAL CENTER,", JACKSON, WY, 83001"
3108,ELITE HOSPITAL KINGWOOD,"23330 HIGHWAY 59 N, KINGWOOD, TX, 77339"
3252,TILDEN COMMUNITY HOSP,", TILDEN, NE, 68781"
3283,SW ALABAMA MED CTR,"33700 HIGHWAY 43, THOMASVILLE, AL, 36784"
3285,RANDOLPH MEDICAL CTR,"59928 HIGHWAY 22, ROANOKE, AL, 36274"
3295,JENKINS COMMUNITY HOSPITAL,"9480 HIGHWAY 805, JENKINS, KY, 41537"
3306,OWYHEE COMMUNITY HEALTH FACILITY,", OWYHEE, NV, 89832"
3309,FT YUMA PHS INDIAN HOSP,", YUMA, AZ, 85366"

In [55]:
# Manually geocoding using Google Maps:
hospitals_master_geo_full.loc[31,'Coordinates'] = '32.930202877035406, -85.96973140660504'
hospitals_master_geo_full.loc[32, 'Coordinates'] = '33.277823411237584, -85.82392071449426'
hospitals_master_geo_full.loc[52, 'Coordinates'] = '32.50500116276686, -87.8366051822052'
hospitals_master_geo_full.loc[57, 'Coordinates'] = '34.24214459224249, -87.59142525335471'
hospitals_master_geo_full.loc[70, 'Coordinates'] = '34.51057625005274, -87.71821035098087'
hospitals_master_geo_full.loc[80, 'Coordinates'] = '60.78806513275268, -161.7870378714418'
hospitals_master_geo_full.loc[106, 'Coordinates'] = '35.759447538436625, -109.04838846732939'
hospitals_master_geo_full.loc[107, 'Coordinates'] = '36.136224365801574, -111.23894322222999'
hospitals_master_geo_full.loc[319, 'Coordinates'] = '34.5417326896706, -117.26579634933447'
hospitals_master_geo_full.loc[1261, 'Coordinates'] = '46.675294970280035, -67.9985363356714'
hospitals_master_geo_full.loc[1500, 'Coordinates'] = '44.87605924328678, -94.3734080753'
hospitals_master_geo_full.loc[1558, 'Coordinates'] = '32.40908420753482, -88.67624746059474'
hospitals_master_geo_full.loc[1573, 'Coordinates'] = '38.19667360943351, -90.39427138159925'
hospitals_master_geo_full.loc[1640, 'Coordinates'] = '40.707780901872006, -99.08179103637423'
hospitals_master_geo_full.loc[1976, 'Coordinates'] = '36.331210106542365, -78.44904591898813'
hospitals_master_geo_full.loc[2002, 'Coordinates'] = '48.83897130249518, -100.60291677408779'
hospitals_master_geo_full.loc[2730, 'Coordinates'] = '32.4269581056858, -95.21596780571046'
hospitals_master_geo_full.loc[2821, 'Coordinates'] = '44.2208487415161, -72.56092004994022'
hospitals_master_geo_full.loc[2877, 'Coordinates'] = '37.20529812094506, -77.45399613503808'
hospitals_master_geo_full.loc[3042, 'Coordinates'] = '43.48087777115584, -110.74957175230679'
hospitals_master_geo_full.loc[3108, 'Coordinates'] = '30.055027146644, -95.25057476031097'
hospitals_master_geo_full.loc[3252, 'Coordinates'] = '42.0475351845259, -97.83778860397436'
hospitals_master_geo_full.loc[3283, 'Coordinates'] = '31.930860609226595, -87.73682227097794'
hospitals_master_geo_full.loc[3285, 'Coordinates'] = '33.158211119503534, -85.38859956679042'
hospitals_master_geo_full.loc[3295, 'Coordinates'] = '37.17154901830917, -82.63410390553726'
hospitals_master_geo_full.loc[3306, 'Coordinates'] = '41.950243466106066, -116.09766907445876'
hospitals_master_geo_full.loc[3309, 'Coordinates'] = '32.736833240713665, -114.61647482181245'

In [50]:
hospitals_master_geo_full['Coordinates'].isna().sum()

np.int64(27)

In [51]:
hospitals_master_geo_full['Coordinates'].isna().sum()

np.int64(27)

I'll also fill in missing RUCA (Rural-Urban Commuting Area code) values, which are a way to designate rural vs urban locations. For that I'll be using a crosswalk downloaded from the USDA.

In [52]:
ruca = pd.read_csv('../data/RUCA-codes-2020-zipcode.csv').rename(columns={'ZIPCode':'Zip','PrimaryRUCA':'RUCA'})[['Zip','RUCA']]

In [53]:
ruca.head(2)

   Zip  RUCA
0    1    10
1    2    10

In [54]:
hospitals_master_geo_full.columns

Index(['CCN', 'Facility Name', 'Address', 'City', 'State', 'Zip', 'County',
       'Emergency Services', 'Hospital Ownership', 'Closed', 'RUCA', 'CBSA',
       'Medicare Payment', 'Number of Beds', 'Closure Date', 'Full Address',
       'State_FIPS', 'County_FIPS', 'Tract_Code', 'Coordinates'],
      dtype='object')

In [55]:
# Merge in RUCA scores
hospitals_master_geo_full = hospitals_master_geo_full.merge(ruca, on='Zip', how='left')

# Coalesce the coordinates column using combine_first
hospitals_master_geo_full['RUCA'] = hospitals_master_geo_full['RUCA_x'].combine_first(hospitals_master_geo_full['RUCA_y'])

# Clean up unneeded columns and drop duplicated rows
hospitals_master_geo_full = hospitals_master_geo_full.drop(columns=['RUCA_x', 'RUCA_y'])

In [57]:
hospitals_master_geo_full['RUCA'].isna().sum()

np.int64(0)

In [56]:
hospitals_master_geo_full.head(2)

,CCN,Facility Name,Address,City,State,Zip,County,Emergency Services,Hospital Ownership,Closed,CBSA,Medicare Payment,Number of Beds,Closure Date,Full Address,State_FIPS,County_FIPS,Tract_Code,Coordinates,RUCA
0,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,Yes,Government - Hospital District or Authority,0,NaN,NaN,NaN,NaT,"1108 ROSS CLARK CIRCLE, DOTHAN, AL, 36301",1.0,69.0,41000.0,"-85.361446991439,31.21566695385",1.0
1,010005,MARSHALL MEDICAL CENTERS,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,Yes,Government - Hospital District or Authority,0,NaN,NaN,NaN,NaT,"2505 U S HIGHWAY 431 NORTH, BOAZ, AL, 35957",1.0,95.0,31200.0,"-86.159366335505,34.221221654827",4.0

Filling in missing census tracts and FIPS codes:

In [59]:
hospitals_master_geo_full['Tract_Code'].isna().sum()

np.int64(523)

Now that we have census tracts for each hospital, we can narrow down the entire dataset to just rural hospitals based on the 
Federal Office of Rural Health Policy's (FORHP) definition of a rural area. I'm utilizing their dataset here as a crosswalk: https://www.hrsa.gov/rural-health/about-us/what-is-rural/data-files

In [67]:
rural = pd.read_excel('../data/rural-health-areas-data-set.xlsx',sheet_name='Census_Tract_Eligibility').rename(columns={'Tract_2020':'Tract_Code'})[['State','Tract_Code','FORHP_Rural']]

In [68]:
rural.head(2)

  State  Tract_Code FORHP_Rural
0    AL     20100.0          No
1    AL     20200.0          No

Next, using latitude and longitude to pull in CBSA information for each hospital.

In [46]:
# 1. Geocode the Address (Convert to Lat/Long)
def get_lat_lon(address_string):
    geolocator = Nominatim(user_agent="cbsa_locator")
    location = geolocator.geocode(address_string)
    if location:
        return Point(location.longitude, location.latitude)
    return None

# The address you want to geolocate
address = "1600 Amphitheatre Parkway, Mountain View, CA"

# Create a DataFrame with your address
df = pd.DataFrame({'address': [address]})
df['geometry'] = df['address'].apply(get_lat_lon)

# Convert to GeoDataFrame (requires WGS 84 / EPSG:4326 coordinate system)
gdf_points = gpd.GeoDataFrame(df, geometry='geometry', crs="EPSG:4326")

# 2. Load the CBSA Shapefile
cbsa_shapefile_path = "../data/tl_2025_us_csa/tl_2025_us_csa.shp" 
cbsa_gdf = gpd.GeoDataFrame.from_file(cbsa_shapefile_path)

# Ensure the shapefile uses the same coordinate system
cbsa_gdf = cbsa_gdf.to_crs("EPSG:4326")

# 3. Spatial Join (Find which CBSA polygon contains the address point)
result = gpd.sjoin(gdf_points, cbsa_gdf, how="left", predicate="within")

# Output the CBSA Name
if not result.empty and 'NAME' in result.columns:
    print(f"The CBSA for this address is: {result['NAME'].iloc[0]}")
else:
    print("Address not found within any recognized CBSA.")

The CBSA for this address is: San Jose-San Francisco-Oakland, CA

Next I'll merge in the NPI numbers. NPI information has been loaded into a SQL database; I'll extract it using a materialized view and merge it into hospitals_master.

In [ ]:
# Create db connection string
db_name = "npi_reg"

connection_string = f"postgresql://postgres:postgres@localhost:5432/{db_name}"

engine = create_engine(connection_string)

In [ ]:
query = '''
    SELECT *
    FROM npi_registry;
'''

with engine.connect() as connection:
    hop_team_nashville_df = pd.read_sql(text(query), con=connection)

hop_team_nashville_df.head()