In [1]:
import pandas as pd

Overall goal: in building a predictive model, we want to successfully predict a hospital closure with enough lead time before it occurs to give the hospital sufficient leeway to make the necessary changes to stay open.

Reading in the full dataset, splitting out columns into categories, and dropping columns that are not needed to create the dataset I'll use for the model:

In [2]:
hospitals_full = pd.read_csv('../data/hospitals_full.csv')

/var/folders/51/zgq0lbb14t13h0_bgn8nntnm0000gn/T/ipykernel_17645/3201850437.py:1: DtypeWarning: Columns (67) have mixed types. Specify dtype option on import or set low_memory=False.
  hospitals_full = pd.read_csv('../data/hospitals_full.csv')

In [3]:
model_data = hospitals_full.drop(columns=['State', 'Zip', 'County','Facility Name','Closed', 'Closure Date','Full Address', 'Prior Name','Tract_Code', 'CBSA_Code', 'CBSA_Title','County_FIPS', 'State_FIPS'])

In [4]:
model_data.shape

(13391, 189)

In [5]:
model_data.head()

,Year,CCN,Medicaid charges,HAC reduction adjustment amount,STATEMENT OF REVENUES AND EXPENSES: Net Income (G3_C1_29),"ADJUSTED SALARIES, Subtotal Salaries",BALANCE SHEET: Prepaid expenses (G_C1THRU4_8),BED DAYS: Total Hospital,Number of Interns & Residents,BALANCE SHEET: Cash on Hand and in Banks (G_C1THRU4_1),...,"Per Capita Phys,Primary Care, Patient Care Non-Fed",Per Capita Short Term Gen Hosp Admissions,Per Capita Short Term General Hosp Beds,Per Capita Total Active D.O.s Non-Federal,Per Capita Total Active M.D.s Non-Federal,Per Capita Total Medicare Inpatient Days Short Term General Hospitals,Per Capita Total Number Hospitals,Percent Persons in Poverty,Population Estimate,"Unemployment Rate, 16+"
0,2010,190044,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000340,0.092921,0.003529,0.0,0.000664,0.241335,0.000065,21.0,61773.0,6.8
1,2011,190044,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000371,0.085783,0.003275,0.0,0.000710,0.230389,0.000065,22.4,61982.0,6.3
2,2012,190044,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000355,0.083247,0.003279,0.0,0.000695,0.244573,0.000065,20.7,61912.0,5.6
3,2013,190044,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000354,0.082776,0.003263,0.0,0.000675,0.262877,0.000064,19.0,62204.0,NaN
4,2014,190044,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000368,0.082386,0.003249,0.0,0.000736,0.269148,0.000048,22.0,62486.0,5.7

#### Feature Engineering:

Creating "General Ownership" column to group hospital types into 'govt','non-profit', and 'for-profit':

In [6]:
model_data['Hospital Type'] = model_data['Hospital Type'].replace('Governmental, Federal', 'Government - Federal')

In [7]:
model_data['General Ownership Type'] = model_data['Hospital Type'].replace({'Voluntary non-profit - Other': 'non-profit',
                                            'Voluntary non-profit - Private': 'non-profit',
                                           'Voluntary non-profit - Church': 'non-profit',
                                           'Government - State': 'govt',
                                           'Government - Local': 'govt', 
                                           'Government - Hospital District or Authority': 'govt', 
                                           'Government - Federal': 'govt', 
                                           'Governmental, Other': 'govt',
                                           'Proprietary, Corporation': 'for-profit', 
                                           'Proprietary': 'for-profit', 
                                           'Tribal': 'govt',
                                           'Physician': 'for-profit',
                                           'Non profit - Corporation': 'non-profit'
                                          }, 
                                         )

In [8]:
model_data['General Ownership Type'].isna().sum()

np.int64(0)

In [9]:
model_data['Hospital Type'].nunique()

13

We might consider excluding hospital type from our model, since it will result in 13 unique features after encoding.

In [10]:
pd.set_option('display.max_rows', None)
model_data.isnull().mean().sort_values(ascending=False)

hf_readm_npatients                                                         1.000000
ami_readm_rate                                                             1.000000
hf_readm_rate                                                              1.000000
pn_mort_rate                                                               1.000000
pn_readm_rate                                                              1.000000
ami_mort_npatients                                                         1.000000
ami_readm_npatients                                                        1.000000
hf_mort_npatients                                                          1.000000
ami_mort_rate                                                              1.000000
pn_mort_npatients                                                          1.000000
pn_readm_npatients                                                         1.000000
all_readm_rate                                                             1.000000
hk_readm_rate                                                              1.000000
all_readm_npatients                                                        1.000000
hk_readm_npatients                                                         1.000000
copd_mort_rate                                                             1.000000
copd_readm_rate                                                            1.000000
stk_mort_rate                                                              1.000000
stk_readm_rate                                                             1.000000
copd_mort_npatients                                                        1.000000
copd_readm_npatients                                                       1.000000
stk_mort_npatients                                                         1.000000
stk_readm_npatients                                                        1.000000
cabg_mort_rate                                                             1.000000
cabg_readm_rate                                                            1.000000
cabg_mort_npatients                                                        1.000000
cabg_readm_npatients                                                       1.000000
hf_mort_rate                                                               1.000000
cac2_share                                                                 0.999477
cac1_share                                                                 0.999477
cac3_share                                                                 0.999477
Donations, Land Improvements                                               0.997984
cac3_denom                                                                 0.997461
cac2_denom                                                                 0.997461
cac1_denom                                                                 0.997461
REIMBURSEMENT SETTLEMENT: Payment to cost ratio                            0.995743
op1_denom                                                                  0.947801
FTE Employees on Payroll                                                   0.943918
op7_share                                                                  0.941827
ami10_share                                                                0.940184
ami2_share                                                                 0.940184
ami7_share                                                                 0.940184
ami8_share                                                                 0.940184
hf1_share                                                                  0.940184
hf2_share                                                                  0.940184
hf3_share                                                                  0.940184
scipcard2_share                                                            0.940184
pn3_share                                                                  0.940184
scipinf10_share                                                            0.940184
scipinf1_share                                                             0.940184
scipinf2_share                                                             0.940184
scipinf3_share                                                             0.940184
scipinf4_share                                                             0.940184
scipinf9_share                                                             0.940184
scipvte1_share                                                             0.940184
pn6_share                                                                  0.940184
scipvte2_share                                                             0.940184
ami10_denom                                                                0.938317
HAC reduction adjustment amount                                            0.922635
op3_denom                                                                  0.919274
ami3_denom                                                                 0.917557
ami4_denom                                                                 0.912628
ami5_denom                                                                 0.910910
ami1_denom                                                                 0.906654
hf4_denom                                                                  0.903368
op2_denom                                                                  0.895826
scipinf10_denom                                                            0.895452
scipinf6_denom                                                             0.892540
pn7_denom                                                                  0.887984
pn4_denom                                                                  0.886790
op6_share                                                                  0.884251
op2_share                                                                  0.884251
op4_share                                                                  0.884251
pn2_denom                                                                  0.884027
pn5_denom                                                                  0.884027
ami2_denom                                                                 0.881040
BALANCE SHEET: Temporary Investments (G_C1THRU4_2)                         0.873721
op6_denom                                                                  0.857442
op7_denom                                                                  0.856471
scipcard2_denom                                                            0.849451
hf3_denom                                                                  0.848107
scipinf9_denom                                                             0.847285
op4_denom                                                                  0.846613
op5_denom                                                                  0.846016
scipinf3_denom                                                             0.843701
scipinf2_denom                                                             0.843626
scipinf1_denom                                                             0.843552
scipvte2_denom                                                             0.841685
scipvte1_denom                                                             0.841535
ami7_denom                                                                 0.840789
ami8_denom                                                                 0.839220
scipinf4_denom                                                             0.836383
hf1_denom                                                                  0.828990
hf2_denom                                                                  0.827795
pn3_denom                                                                  0.827571
pn6_denom                                                                  0.826675
Financial Indicators: SOLVENCY Interest Coverage Ratio                     0.793294
TRIAL BALANCE OF EXPENSE ACCOUNTS: Interest Expense (A_C2_113)             0.792174
HVBP payment adjustment amount                                             0.723396
NUMBER OF BEDS: ICU                                                        0.685460
Total cost of charity care                                                 0.682100
Medicaid charges                                                           0.669405
S-10 DATA: Medicaid Costs                                                  0.669405
Net Revenue from Medicaid                                                  0.668807
Total Bad Debt expense                                                     0.667911
Cost of Uncompensated Care                                                 0.662460
Cost To Charge Ratio                                                       0.658427
Financial Indicators: LIQUIDITY acid-test ratio (variation)                0.643791
BALANCE SHEET: Prepaid expenses (G_C1THRU4_8)                              0.636323
BALANCE SHEET: Inventory (G_C1THRU4_7)                                     0.603764
Financial Indicators: LIQUIDITY cash ratio                                 0.603316
BALANCE SHEET: Cash on Hand and in Banks (G_C1THRU4_1)                     0.595027
BALANCE SHEET: Accounts Receivable (G_C1THRU4_4)                           0.594653
Financial Indicators: LIQUIDITY current ratio                              0.592637
IPPS Payment amount (unadjusted)                                           0.592487
IPPS Interim payment                                                       0.592413
BALANCE SHEET: Total Current Assets (G_C1THRU4_11)                         0.592189
Financial Indicators: SOLVENCY Debt-to-Equity Ratio                        0.592114
Financial Indicators: SOLVENCY Debt Ratio                                  0.592114
Financial Indicators: SOLVENCY Equity Ratio                                0.592114
Financial Indicators: Total Net Assets                                     0.592039
Total Liabilities                                                          0.592039
Financial Indicators: LIQUIDITY acid-test ratio                            0.592039
BALANCE SHEET: Total Current Liabilities (G_C1THRU4_45)                    0.592039
Financial Indicators: SOLVENCY total assets less total liabilities         0.592039
Financial Indicators: EFFICIENCY asset turnover ratio                      0.591741
BALANCE SHEET: Total Assets (G_C1THRU4_36)                                 0.591666
Financial Indicators: Net Profit Margin                                    0.591591
Financial Indicators: Operating Profit                                     0.591591
STATEMENT OF REVENUES AND EXPENSES: Net Patient Revenue (G3_C1_3)          0.591591
Financial Indicators: Operating Profit Margin                              0.591591
Financial Indicators: EFFICIENCY Accounts Receivable Turnover Ratio        0.591591
ADJUSTED SALARIES, Subtotal Salaries                                       0.589052
REIMBURSEMENT SETTLEMENT: Subtotal                                         0.586588
REIMBURSEMENT SETTLEMENT: Interim payments                                 0.586588
Number of Interns & Residents                                              0.586140
RECONCILIATION OF CAPITAL COST CENTERS: Depreciation, Total (A7_3_C9_3)    0.585617
Total Days Title XVIII                                                     0.585468
Total Inpatient Days                                                       0.584124
Total discharges                                                           0.584049
NUMBER OF BEDS: Adults & Pediatrics                                        0.583974
NUMBER OF BEDS: Total Hospital                                             0.583974
BED DAYS: Total Hospital                                                   0.583974
Total Charges                                                              0.583750
Total Salaries                                                             0.583750
Total Costs                                                                0.583750
STATEMENT OF REVENUES AND EXPENSES: Net Income (G3_C1_29)                  0.583750
Financial Indicators: Cash Reserves                                        0.582929
pain_score                                                                 0.534165
Per Capita Personal Income                                                 0.440445
% <65 without Health Insurance                                             0.384437
Dist Hosp By 60 - 79% Util Rate Short Term General Hospitals               0.381077
Per Capita # Short Term General Hosps                                      0.381077
Per Capita Hospital Admissions                                             0.381077
Per Capita Hospital Beds                                                   0.381077
Per Capita Inpatient Days in ST Gen Hosp                                   0.381077
Dist Hosp By 00 - 39% Util Rate Short Term General Hospitals               0.381077
Dist Hosp By 40 - 59% Util Rate Short Term General Hospitals               0.381077
Per Capita Short Term Gen Hosp Admissions                                  0.381077
Dist Hosp By 80+% Util Rate Short Term General Hospitals                   0.381077
Per Capita Short Term General Hosp Beds                                    0.381077
Per Capita Total Medicare Inpatient Days Short Term General Hospitals      0.381077
Per Capita Total Number Hospitals                                          0.381077
Percent Persons in Poverty                                                 0.329998
Median Household Income                                                    0.329774
Unemployment Rate, 16+                                                     0.328430
Per Capita Total Active D.O.s Non-Federal                                  0.325666
Per Capita Phys,Primary Care, Patient Care Non-Fed                         0.325666
Per Capita Total Active M.D.s Non-Federal                                  0.325666
Population Estimate                                                        0.271003
understood_score                                                           0.245837
explain_score                                                              0.072362
nsurveys                                                                   0.072063
recommend_score                                                            0.072063
rrate                                                                      0.072063
clean_score                                                                0.072063
commdoc_score                                                              0.072063
commnurse_score                                                            0.072063
help_score                                                                 0.072063
overall_score                                                              0.072063
quiet_score                                                                0.072063
info_score                                                                 0.072063
Year                                                                       0.000000
CCN                                                                        0.000000
Hospital Type                                                              0.000000
Closure Proximity                                                          0.000000
Metro_Status                                                               0.000000
RUCA                                                                       0.000000
Emergency Services                                                         0.000000
General Ownership Type                                                     0.000000
dtype: float64

In [11]:
# Drop columns that are more than 80% NaNs
model_data = model_data.loc[:, model_data.isnull().mean() <= 0.80]

In [12]:
model_data.shape

(13391, 94)

This still leaves us with 91 features (94 columns minus 2 id columns and 1 target column)

Breaking down features into large scale types:

In [13]:
print(list(model_data.columns))

['Year', 'CCN', 'Medicaid charges', 'STATEMENT OF REVENUES AND EXPENSES: Net Income (G3_C1_29)', 'ADJUSTED SALARIES, Subtotal Salaries', 'BALANCE SHEET: Prepaid expenses (G_C1THRU4_8)', 'BED DAYS: Total Hospital', 'Number of Interns & Residents', 'BALANCE SHEET: Cash on Hand and in Banks (G_C1THRU4_1)', 'Cost To Charge Ratio', 'Total discharges', 'Cost of Uncompensated Care', 'BALANCE SHEET: Accounts Receivable (G_C1THRU4_4)', 'Total Salaries', 'BALANCE SHEET: Total Assets (G_C1THRU4_36)', 'BALANCE SHEET: Total Current Assets (G_C1THRU4_11)', 'REIMBURSEMENT SETTLEMENT: Interim payments', 'Total Bad Debt expense', 'TRIAL BALANCE OF EXPENSE ACCOUNTS: Interest Expense (A_C2_113)', 'NUMBER OF BEDS: Adults & Pediatrics', 'NUMBER OF BEDS: Total Hospital', 'Total Inpatient Days', 'Total Days Title XVIII', 'Total cost of charity care', 'Total Costs', 'NUMBER OF BEDS: ICU', 'Total Charges', 'Net Revenue from Medicaid', 'Total Liabilities', 'HVBP payment adjustment amount', 'REIMBURSEMENT SETTLEMENT: Subtotal', 'IPPS Interim payment', 'IPPS Payment amount (unadjusted)', 'RECONCILIATION OF CAPITAL COST CENTERS: Depreciation, Total (A7_3_C9_3)', 'BALANCE SHEET: Total Current Liabilities (G_C1THRU4_45)', 'BALANCE SHEET: Inventory (G_C1THRU4_7)', 'STATEMENT OF REVENUES AND EXPENSES: Net Patient Revenue (G3_C1_3)', 'Financial Indicators: Total Net Assets', 'S-10 DATA: Medicaid Costs', 'Financial Indicators: Cash Reserves', 'Financial Indicators: Net Profit Margin', 'Financial Indicators: Operating Profit', 'Financial Indicators: Operating Profit Margin', 'Financial Indicators: LIQUIDITY current ratio', 'Financial Indicators: LIQUIDITY acid-test ratio', 'Financial Indicators: LIQUIDITY acid-test ratio (variation)', 'Financial Indicators: LIQUIDITY cash ratio', 'Financial Indicators: SOLVENCY Debt-to-Equity Ratio', 'Financial Indicators: SOLVENCY Debt Ratio', 'Financial Indicators: SOLVENCY Equity Ratio', 'Financial Indicators: SOLVENCY Interest Coverage Ratio', 'Financial Indicators: SOLVENCY total assets less total liabilities', 'Financial Indicators: EFFICIENCY asset turnover ratio', 'Financial Indicators: EFFICIENCY Accounts Receivable Turnover Ratio', 'Emergency Services', 'RUCA', 'Metro_Status', 'Closure Proximity', 'Hospital Type', 'nsurveys', 'rrate', 'clean_score', 'commdoc_score', 'commnurse_score', 'explain_score', 'help_score', 'info_score', 'overall_score', 'pain_score', 'quiet_score', 'recommend_score', 'understood_score', '% <65 without Health Insurance', 'Dist Hosp By 00 - 39% Util Rate Short Term General Hospitals', 'Dist Hosp By 40 - 59% Util Rate Short Term General Hospitals', 'Dist Hosp By 60 - 79% Util Rate Short Term General Hospitals', 'Dist Hosp By 80+% Util Rate Short Term General Hospitals', 'Median Household Income', 'Per Capita # Short Term General Hosps', 'Per Capita Hospital Admissions', 'Per Capita Hospital Beds', 'Per Capita Inpatient Days in ST Gen Hosp', 'Per Capita Personal Income', 'Per Capita Phys,Primary Care, Patient Care Non-Fed', 'Per Capita Short Term Gen Hosp Admissions', 'Per Capita Short Term General Hosp Beds', 'Per Capita Total Active D.O.s Non-Federal', 'Per Capita Total Active M.D.s Non-Federal', 'Per Capita Total Medicare Inpatient Days Short Term General Hospitals', 'Per Capita Total Number Hospitals', 'Percent Persons in Poverty', 'Population Estimate', 'Unemployment Rate, 16+', 'General Ownership Type']

In [14]:
id_cols = ['Year','CCN']
target_col = ['Closure Proximity']
hospital_char_cols = ['General Ownership Type','Emergency Services','Hospital Type']
financial_cols = ['BALANCE SHEET: Total Assets (G_C1THRU4_36)', 'BED DAYS: Total Hospital', 'REIMBURSEMENT SETTLEMENT: Interim payments', 
                  'IPPS Interim payment', 'BALANCE SHEET: Cash on Hand and in Banks (G_C1THRU4_1)', 
                  'BALANCE SHEET: Total Current Liabilities (G_C1THRU4_45)', 'Total cost of charity care', 
                  'HVBP payment adjustment amount', 'Total discharges', 'Total Salaries', 
                  'BALANCE SHEET: Accounts Receivable (G_C1THRU4_4)', 'Net Revenue from Medicaid', 
                  'Total Bad Debt expense', 'Total Charges', 'ADJUSTED SALARIES, Subtotal Salaries', 
                  'NUMBER OF BEDS: Adults & Pediatrics', 'Total Costs', 'BALANCE SHEET: Prepaid expenses (G_C1THRU4_8)', 
                  'BALANCE SHEET: Total Current Assets (G_C1THRU4_11)', 'Cost To Charge Ratio', 'REIMBURSEMENT SETTLEMENT: Subtotal', 
                  'Number of Interns & Residents', 'RECONCILIATION OF CAPITAL COST CENTERS: Depreciation, Total (A7_3_C9_3)', 
                  'Total Inpatient Days', 'STATEMENT OF REVENUES AND EXPENSES: Net Patient Revenue (G3_C1_3)', 
                  'NUMBER OF BEDS: Total Hospital', 'NUMBER OF BEDS: ICU', 'STATEMENT OF REVENUES AND EXPENSES: Net Income (G3_C1_29)', 
                  'BALANCE SHEET: Inventory (G_C1THRU4_7)', 'IPPS Payment amount (unadjusted)', 
                  'TRIAL BALANCE OF EXPENSE ACCOUNTS: Interest Expense (A_C2_113)', 'Cost of Uncompensated Care', 'Medicaid charges', 
                  'Total Liabilities', 'Total Days Title XVIII', 'Financial Indicators: Total Net Assets', 'S-10 DATA: Medicaid Costs', 
                  'Financial Indicators: Cash Reserves', 'Financial Indicators: Net Profit Margin', 'Financial Indicators: Operating Profit', 
                  'Financial Indicators: Operating Profit Margin', 'Financial Indicators: LIQUIDITY current ratio', 
                  'Financial Indicators: LIQUIDITY acid-test ratio', 'Financial Indicators: LIQUIDITY acid-test ratio (variation)', 
                  'Financial Indicators: LIQUIDITY cash ratio', 'Financial Indicators: SOLVENCY Debt-to-Equity Ratio', 
                  'Financial Indicators: SOLVENCY Debt Ratio', 'Financial Indicators: SOLVENCY Equity Ratio', 
                  'Financial Indicators: SOLVENCY Interest Coverage Ratio', 'Financial Indicators: SOLVENCY total assets less total liabilities', 
                  'Financial Indicators: EFFICIENCY asset turnover ratio', 'Financial Indicators: EFFICIENCY Accounts Receivable Turnover Ratio']
hosp_quality_cols = ['nsurveys', 'rrate', 'clean_score', 'commdoc_score', 'commnurse_score', 'explain_score', 'help_score', 
                     'info_score', 'overall_score', 'pain_score', 'quiet_score', 'recommend_score', 'understood_score']
demographic_cols = ['RUCA','Metro_Status','% <65 without Health Insurance', 'Dist Hosp By 00 - 39% Util Rate Short Term General Hospitals', 
                    'Dist Hosp By 40 - 59% Util Rate Short Term General Hospitals', 
                    'Dist Hosp By 60 - 79% Util Rate Short Term General Hospitals', 
                    'Dist Hosp By 80+% Util Rate Short Term General Hospitals', 
                    'Median Household Income', 'Per Capita # Short Term General Hosps', 'Per Capita Hospital Admissions', 
                    'Per Capita Hospital Beds', 'Per Capita Inpatient Days in ST Gen Hosp', 'Per Capita Personal Income', 
                    'Per Capita Phys,Primary Care, Patient Care Non-Fed', 'Per Capita Short Term Gen Hosp Admissions', 
                    'Per Capita Short Term General Hosp Beds', 'Per Capita Total Active D.O.s Non-Federal', 
                    'Per Capita Total Active M.D.s Non-Federal', 'Per Capita Total Medicare Inpatient Days Short Term General Hospitals', 
                    'Per Capita Total Number Hospitals', 'Percent Persons in Poverty', 'Population Estimate', 'Unemployment Rate, 16+']

In [15]:
len(id_cols) + len(target_col) + len(hospital_char_cols) + len(financial_cols) + len(hosp_quality_cols) + len(demographic_cols) == len(model_data.columns)

True

Are there any hospitals that we don't have any data for?

In [16]:
model_data[model_data[financial_cols + hosp_quality_cols + demographic_cols].isna().all(axis=1)]

Empty DataFrame
Columns: [Year, CCN, Medicaid charges, STATEMENT OF REVENUES AND EXPENSES: Net Income (G3_C1_29), ADJUSTED SALARIES, Subtotal Salaries, BALANCE SHEET: Prepaid expenses (G_C1THRU4_8), BED DAYS: Total Hospital, Number of Interns & Residents, BALANCE SHEET: Cash on Hand and in Banks (G_C1THRU4_1), Cost To Charge Ratio, Total discharges, Cost of Uncompensated Care, BALANCE SHEET: Accounts Receivable (G_C1THRU4_4), Total Salaries, BALANCE SHEET: Total Assets (G_C1THRU4_36), BALANCE SHEET: Total Current Assets (G_C1THRU4_11), REIMBURSEMENT SETTLEMENT: Interim payments, Total Bad Debt expense, TRIAL BALANCE OF EXPENSE ACCOUNTS: Interest Expense (A_C2_113), NUMBER OF BEDS: Adults & Pediatrics, NUMBER OF BEDS: Total Hospital, Total Inpatient Days, Total Days Title XVIII, Total cost of charity care, Total Costs, NUMBER OF BEDS: ICU, Total Charges, Net Revenue from Medicaid, Total Liabilities, HVBP payment adjustment amount, REIMBURSEMENT SETTLEMENT: Subtotal, IPPS Interim payment, IPPS Payment amount (unadjusted), RECONCILIATION OF CAPITAL COST CENTERS: Depreciation, Total (A7_3_C9_3), BALANCE SHEET: Total Current Liabilities (G_C1THRU4_45), BALANCE SHEET: Inventory (G_C1THRU4_7), STATEMENT OF REVENUES AND EXPENSES: Net Patient Revenue (G3_C1_3), Financial Indicators: Total Net Assets, S-10 DATA: Medicaid Costs, Financial Indicators: Cash Reserves, Financial Indicators: Net Profit Margin, Financial Indicators: Operating Profit, Financial Indicators: Operating Profit Margin, Financial Indicators: LIQUIDITY current ratio, Financial Indicators: LIQUIDITY acid-test ratio, Financial Indicators: LIQUIDITY acid-test ratio (variation), Financial Indicators: LIQUIDITY cash ratio, Financial Indicators: SOLVENCY Debt-to-Equity Ratio, Financial Indicators: SOLVENCY Debt Ratio, Financial Indicators: SOLVENCY Equity Ratio, Financial Indicators: SOLVENCY Interest Coverage Ratio, Financial Indicators: SOLVENCY total assets less total liabilities, Financial Indicators: EFFICIENCY asset turnover ratio, Financial Indicators: EFFICIENCY Accounts Receivable Turnover Ratio, Emergency Services, RUCA, Metro_Status, Closure Proximity, Hospital Type, nsurveys, rrate, clean_score, commdoc_score, commnurse_score, explain_score, help_score, info_score, overall_score, pain_score, quiet_score, recommend_score, understood_score, % <65 without Health Insurance, Dist Hosp By 00 - 39% Util Rate Short Term General Hospitals, Dist Hosp By 40 - 59% Util Rate Short Term General Hospitals, Dist Hosp By 60 - 79% Util Rate Short Term General Hospitals, Dist Hosp By 80+% Util Rate Short Term General Hospitals, Median Household Income, Per Capita # Short Term General Hosps, Per Capita Hospital Admissions, Per Capita Hospital Beds, Per Capita Inpatient Days in ST Gen Hosp, Per Capita Personal Income, Per Capita Phys,Primary Care, Patient Care Non-Fed, Per Capita Short Term Gen Hosp Admissions, Per Capita Short Term General Hosp Beds, Per Capita Total Active D.O.s Non-Federal, Per Capita Total Active M.D.s Non-Federal, Per Capita Total Medicare Inpatient Days Short Term General Hospitals, Per Capita Total Number Hospitals, Percent Persons in Poverty, Population Estimate, Unemployment Rate, 16+, General Ownership Type]
Index: []

[0 rows x 94 columns]

For every hospital in the dataset, we have at least some financial data, quality data, and/or demographic data.

Ensuring all of the data types are appropriate for the values they represent:

In [17]:
model_data.dtypes

Year                                                                         int64
CCN                                                                          int64
Medicaid charges                                                           float64
STATEMENT OF REVENUES AND EXPENSES: Net Income (G3_C1_29)                  float64
ADJUSTED SALARIES, Subtotal Salaries                                       float64
BALANCE SHEET: Prepaid expenses (G_C1THRU4_8)                              float64
BED DAYS: Total Hospital                                                   float64
Number of Interns & Residents                                              float64
BALANCE SHEET: Cash on Hand and in Banks (G_C1THRU4_1)                     float64
Cost To Charge Ratio                                                       float64
Total discharges                                                           float64
Cost of Uncompensated Care                                                 float64
BALANCE SHEET: Accounts Receivable (G_C1THRU4_4)                           float64
Total Salaries                                                             float64
BALANCE SHEET: Total Assets (G_C1THRU4_36)                                 float64
BALANCE SHEET: Total Current Assets (G_C1THRU4_11)                         float64
REIMBURSEMENT SETTLEMENT: Interim payments                                 float64
Total Bad Debt expense                                                     float64
TRIAL BALANCE OF EXPENSE ACCOUNTS: Interest Expense (A_C2_113)             float64
NUMBER OF BEDS: Adults & Pediatrics                                        float64
NUMBER OF BEDS: Total Hospital                                             float64
Total Inpatient Days                                                       float64
Total Days Title XVIII                                                     float64
Total cost of charity care                                                 float64
Total Costs                                                                float64
NUMBER OF BEDS: ICU                                                        float64
Total Charges                                                              float64
Net Revenue from Medicaid                                                  float64
Total Liabilities                                                          float64
HVBP payment adjustment amount                                             float64
REIMBURSEMENT SETTLEMENT: Subtotal                                         float64
IPPS Interim payment                                                       float64
IPPS Payment amount (unadjusted)                                           float64
RECONCILIATION OF CAPITAL COST CENTERS: Depreciation, Total (A7_3_C9_3)    float64
BALANCE SHEET: Total Current Liabilities (G_C1THRU4_45)                    float64
BALANCE SHEET: Inventory (G_C1THRU4_7)                                     float64
STATEMENT OF REVENUES AND EXPENSES: Net Patient Revenue (G3_C1_3)          float64
Financial Indicators: Total Net Assets                                     float64
S-10 DATA: Medicaid Costs                                                  float64
Financial Indicators: Cash Reserves                                        float64
Financial Indicators: Net Profit Margin                                    float64
Financial Indicators: Operating Profit                                     float64
Financial Indicators: Operating Profit Margin                              float64
Financial Indicators: LIQUIDITY current ratio                              float64
Financial Indicators: LIQUIDITY acid-test ratio                            float64
Financial Indicators: LIQUIDITY acid-test ratio (variation)                float64
Financial Indicators: LIQUIDITY cash ratio                                 float64
Financial Indicators: SOLVENCY Debt-to-Equity Ratio                        float64
Financial Indicators: SOLVENCY Debt Ratio                                  float64
Financial Indicators: SOLVENCY Equity Ratio                                float64
Financial Indicators: SOLVENCY Interest Coverage Ratio                     float64
Financial Indicators: SOLVENCY total assets less total liabilities         float64
Financial Indicators: EFFICIENCY asset turnover ratio                      float64
Financial Indicators: EFFICIENCY Accounts Receivable Turnover Ratio        float64
Emergency Services                                                          object
RUCA                                                                       float64
Metro_Status                                                                object
Closure Proximity                                                            int64
Hospital Type                                                               object
nsurveys                                                                   float64
rrate                                                                      float64
clean_score                                                                float64
commdoc_score                                                              float64
commnurse_score                                                            float64
explain_score                                                              float64
help_score                                                                 float64
info_score                                                                 float64
overall_score                                                              float64
pain_score                                                                 float64
quiet_score                                                                float64
recommend_score                                                            float64
understood_score                                                           float64
% <65 without Health Insurance                                             float64
Dist Hosp By 00 - 39% Util Rate Short Term General Hospitals               float64
Dist Hosp By 40 - 59% Util Rate Short Term General Hospitals               float64
Dist Hosp By 60 - 79% Util Rate Short Term General Hospitals               float64
Dist Hosp By 80+% Util Rate Short Term General Hospitals                   float64
Median Household Income                                                    float64
Per Capita # Short Term General Hosps                                      float64
Per Capita Hospital Admissions                                             float64
Per Capita Hospital Beds                                                   float64
Per Capita Inpatient Days in ST Gen Hosp                                   float64
Per Capita Personal Income                                                 float64
Per Capita Phys,Primary Care, Patient Care Non-Fed                         float64
Per Capita Short Term Gen Hosp Admissions                                  float64
Per Capita Short Term General Hosp Beds                                    float64
Per Capita Total Active D.O.s Non-Federal                                  float64
Per Capita Total Active M.D.s Non-Federal                                  float64
Per Capita Total Medicare Inpatient Days Short Term General Hospitals      float64
Per Capita Total Number Hospitals                                          float64
Percent Persons in Poverty                                                 float64
Population Estimate                                                        float64
Unemployment Rate, 16+                                                     float64
General Ownership Type                                                      object
dtype: object

In [18]:
model_data['Closure Proximity'] = model_data['Closure Proximity'].astype(int)

In [19]:
model_data['RUCA'] = model_data['RUCA'].astype(object)

#### Data Preprocessing:

In [20]:
numeric_features = [col for col in model_data.select_dtypes('number').columns if col not in ['Year','CCN','Closure Proximity']]

In [21]:
categorical_features = [col for col in model_data.select_dtypes('object').columns]

In [22]:
model_data[categorical_features].isnull().mean().sort_values(ascending=False)

Emergency Services        0.0
RUCA                      0.0
Metro_Status              0.0
Hospital Type             0.0
General Ownership Type    0.0
dtype: float64

None of our categorical variables have missing values, so we don't need to worry about imputing them.

Next step: decide which type of imputer and scaler is best to use for the numeric features.

In [ ]:
# Numeric pipeline
numeric_transformer = Pipeline(steps=[
    # Applying an iterative imputer to fill missing values
    ("imputer", IterativeImputer(random_state=0, verbose=2)),
    # Applying a MaxAbsScaler (better than StandardScaler for sparse inputs or inputs that are not normally distributed)
    ("scaler", MaxAbsScaler())
])

# Categorical pipeline
categorical_transformer = Pipeline(steps=[
    ("encoder", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
])

# Combine all the transformations into 1 preprocessor
# Using ColumnTransformer to select specific columns and apply transformations
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)
    ],
    remainder="passthrough",
    verbose_feature_names_out=False
)

pipe = Pipeline(
    steps=[("preprocessor", preprocessor)]
)

In [ ]:
# Train/test/validation split:

#### Hyperparameter Tuning:

Here, we'll split our data using 5-fold validation and apply the pre-processor pipeline (scaling and filling in missing values). 

Once we have our pre-processed cross-validation datasets, we'll fit a model to each of the training sets and evaluate its effectiveness via the corresponding validation set.